### ISSUE TITLE
path.join arguments aren't strings on Windows

### ISSUE THREAD

**Issue by dandv** [lookback/meteor-emails#29]
`meteor run` in the `example` dies on Windows with

```
=> Exited with code: 8
W20150717-05:27:39.607(-7)? (STDERR)
W20150717-05:27:39.608(-7)? (STDERR) C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20150717-05:27:39.609(-7)? (STDERR)                                            throw(ex);
W20150717-05:27:39.609(-7)? (STDERR)                                                  ^
W20150717-05:27:39.609(-7)? (STDERR) TypeError: Arguments to path.join must be strings
W20150717-05:27:39.610(-7)? (STDERR)     at f (path.js:204:15)
W20150717-05:27:39.610(-7)? (STDERR)     at Object.filter (native)
W20150717-05:27:39.610(-7)? (STDERR)     at Object.exports.join (path.js:209:40)
W20150717-05:27:39.615(-7)? (STDERR)     at __coffeescriptShare (packages/lookback:emails/utils.coffee:24:15)
W20150717-05:27:39.615(-7)? (STDERR)     at packages/lookback:emails/utils.coffee:3:1
W20150717-05:27:39.615(-7)? (STDERR)     at packages/lookback:emails/emails.coffee:8:1
W20150717-05:27:39.615(-7)? (STDERR)     at c:\prg\met\meteor-emails\example\.meteor\local\build\programs\server\boot.js:222:10
W20150717-05:27:39.616(-7)? (STDERR)     at Array.forEach (native)
W20150717-05:27:39.616(-7)? (STDERR)     at Function._.each._.forEach (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20150717-05:27:39.616(-7)? (STDERR)     at c:\prg\met\meteor-emails\example\.meteor\local\build\programs\server\boot.js:117:5
```

**Comment by johanbrook** [comment]
Interesting, thank you. This is due to this:

```
ROOT = path.join(process.env.PWD, 'private')
```

`process.env.PWD` probably isn't available on Windows.
