### ISSUE TITLE
Error when installing in new project

### ISSUE THREAD

**Issue by bduff9** [lookback/meteor-emails#92]
Hi there, love the project despite some initial pains with getting it set up.

I am currently running into an issue where trying to install lookback in a new project fails with the following:

```
$ meteor add lookback:emails
 => Errors while adding packages:

While loading package lookback:emails@0.7.7:
error: Command failed: C:\WINDOWS\system32\cmd.exe /c
C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd
rebuild --update-binary
Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/win32-ia32-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [
'C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-beta.32\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe',
gyp verb cli
'C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.5.0 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable
"C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle\python\python.exe"
in the PATH
gyp verb `which` succeeded
C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle\python\python.exe C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle\python\python.exe gyp verb check python version
`C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle\python\python.exe

-c "import platform; print(platform.python_version());"` returned: "2.7.12\r\n"
gyp verb get node dir compiling against specified --nodedir dev files:
C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle
gyp verb build dir attempting to create "build" dir:
C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\.temp-18lxdyr.ndtc\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created?
C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\.temp-18lxdyr.ndtc\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file:
C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\.temp-18lxdyr.ndtc\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file:
C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\.temp-18lxdyr.ndtc\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file:
C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\.temp-18lxdyr.ndtc\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn
C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle\python\python.exe gyp info spawn args [
'C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args
'C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\.temp-18lxdyr.ndtc\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args
'C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args
'C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-beta.32\\mt-os.windows.x86_32\\dev_bundle\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args
'-Dnode_root_dir=C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-beta.32\\mt-os.windows.x86_32\\dev_bundle',
gyp info spawn args
'-Dnode_gyp_dir=C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args
'-Dmodule_root_dir=C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\.temp-18lxdyr.ndtc\\node_modules\\node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args
'C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\.temp-18lxdyr.ndtc\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp:
C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle\common.gypi
not found (cwd:
C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\.temp-18lxdyr.ndtc\node_modules\node-sass)
while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit
(C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command
"C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-beta.32\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd
C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\.temp-18lxdyr.ndtc\node_modules\node-sass
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Duffey\AppData\Roaming\npm-cache\_logs\2017-09-27T19_31_13_837Z-debug.log
Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/win32-ia32-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [
'C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-beta.32\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe',
gyp verb cli
'C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.5.0 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable
"C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle\python\python.exe"
in the PATH
gyp verb `which` succeeded
C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle\python\python.exe C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle\python\python.exe gyp verb check python version
`C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle\python\python.exe

-c "import platform; print(platform.python_version());"` returned: "2.7.12\r\n"
gyp verb get node dir compiling against specified --nodedir dev files:
C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle
gyp verb build dir attempting to create "build" dir:
C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\.temp-18lxdyr.ndtc\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created?
C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\.temp-18lxdyr.ndtc\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file:
C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\.temp-18lxdyr.ndtc\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file:
C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\.temp-18lxdyr.ndtc\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file:
C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\.temp-18lxdyr.ndtc\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn
C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle\python\python.exe gyp info spawn args [
'C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args
'C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\.temp-18lxdyr.ndtc\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args
'C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args
'C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-beta.32\\mt-os.windows.x86_32\\dev_bundle\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args
'-Dnode_root_dir=C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-beta.32\\mt-os.windows.x86_32\\dev_bundle',
gyp info spawn args
'-Dnode_gyp_dir=C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args
'-Dmodule_root_dir=C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\.temp-18lxdyr.ndtc\\node_modules\\node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args
'C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\.temp-18lxdyr.ndtc\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp:
C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.6.0-beta.32\mt-os.windows.x86_32\dev_bundle\common.gypi
not found (cwd:
C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\.temp-18lxdyr.ndtc\node_modules\node-sass)
while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit
(C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command
"C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-beta.32\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Duffey\\AppData\\Local\\.meteor\\packages\\lookback_emails\\0.7.7\\npm\\example\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd
C:\Users\Duffey\AppData\Local\.meteor\packages\lookback_emails\0.7.7\npm\example\node_modules\.temp-18lxdyr.ndtc\node_modules\node-sass
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Duffey\AppData\Roaming\npm-cache\_logs\2017-09-27T19_31_13_837Z-debug.log
```

It looks like it's trying to download node-sass so I went to the URL that's giving a 404 and it does seem to not be there.  Since I just installed this in another project in August, I would guess something changed on node-sass's side but unsure how to proceed.  Any help would be appreciated.  Thanks!

**Comment by johanbrook** [comment]
Hey!

That's weird: this project actually doesn't have a hard dependency on any Meteor or node sass library. Are you using any in your app?

**Comment by bduff9** [comment]
Thanks for your reply.  I cannot quite figure this out, but it does seem to have resolved itself.  Basically, this worked on my Ubuntu and not my Windows machine.  Over the weekend, I was working on it on Ubuntu, and updated Meteor to the latest release candidate.  When I pulled that change onto my work PC, it now works to add this as well.

So, the error indicated to me it was an issue with this plugin since everything else worked but adding this.  However, the fact that you don't have any dependencies on node-sass and that the resolution seemed to be updating meteor point to something else entirely.  Regardless, thank you for your response and for re-opening the issues here.

**Comment by johanbrook** [comment]
Gotcha. Yes, binary dependencies, like `node-sass`, have always been a pain in Meteor. The stack traces don't always point to the real culprit.
